// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

// Protobuf Java Version: 3.25.6
package com.microservices.grpc.order_product.entities;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order_product.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 product_id = 2;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>.order_product.OrderState state = 4;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.order_product.OrderState state = 4;</code>
   * @return The state.
   */
  com.microservices.grpc.order_product.entities.OrderState getState();
}
