// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

// Protobuf Java Version: 3.25.6
package com.microservices.grpc.order_product.entities;

/**
 * Protobuf enum {@code order_product.OrderState}
 */
public enum OrderState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CREATED = 0;</code>
   */
  CREATED(0),
  /**
   * <code>PROCESSING = 1;</code>
   */
  PROCESSING(1),
  /**
   * <code>FAILED = 2;</code>
   */
  FAILED(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CREATED = 0;</code>
   */
  public static final int CREATED_VALUE = 0;
  /**
   * <code>PROCESSING = 1;</code>
   */
  public static final int PROCESSING_VALUE = 1;
  /**
   * <code>FAILED = 2;</code>
   */
  public static final int FAILED_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OrderState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OrderState forNumber(int value) {
    switch (value) {
      case 0: return CREATED;
      case 1: return PROCESSING;
      case 2: return FAILED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OrderState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OrderState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OrderState>() {
          public OrderState findValueByNumber(int number) {
            return OrderState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.microservices.grpc.order_product.entities.Entities.getDescriptor().getEnumTypes().get(1);
  }

  private static final OrderState[] VALUES = values();

  public static OrderState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OrderState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:order_product.OrderState)
}

