// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

// Protobuf Java Version: 3.25.6
package com.microservices.grpc.order_product.entities;

/**
 * <pre>
 * Entity-related enums
 * </pre>
 *
 * Protobuf enum {@code order_product.ProductState}
 */
public enum ProductState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>AVAILABLE = 0;</code>
   */
  AVAILABLE(0),
  /**
   * <code>OUT_OF_STOCK = 1;</code>
   */
  OUT_OF_STOCK(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>AVAILABLE = 0;</code>
   */
  public static final int AVAILABLE_VALUE = 0;
  /**
   * <code>OUT_OF_STOCK = 1;</code>
   */
  public static final int OUT_OF_STOCK_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProductState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ProductState forNumber(int value) {
    switch (value) {
      case 0: return AVAILABLE;
      case 1: return OUT_OF_STOCK;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProductState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProductState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProductState>() {
          public ProductState findValueByNumber(int number) {
            return ProductState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.microservices.grpc.order_product.entities.Entities.getDescriptor().getEnumTypes().get(0);
  }

  private static final ProductState[] VALUES = values();

  public static ProductState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProductState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:order_product.ProductState)
}

