// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

// Protobuf Java Version: 3.25.6
package com.microservices.grpc.order_product.dto;

public interface CreateOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order_product.CreateOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 product_id = 1;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();
}
