// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

// Protobuf Java Version: 3.25.6
package com.microservices.grpc.order_product.dto;

public interface CreateOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order_product.CreateOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.order_product.Order order = 1;</code>
   * @return Whether the order field is set.
   */
  boolean hasOrder();
  /**
   * <code>.order_product.Order order = 1;</code>
   * @return The order.
   */
  com.microservices.grpc.order_product.entities.Order getOrder();
  /**
   * <code>.order_product.Order order = 1;</code>
   */
  com.microservices.grpc.order_product.entities.OrderOrBuilder getOrderOrBuilder();
}
