// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

// Protobuf Java Version: 3.25.6
package com.microservices.grpc.order_product.dto;

public interface GetProductByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order_product.GetProductByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 product_id = 1;</code>
   * @return The productId.
   */
  int getProductId();
}
