// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

// Protobuf Java Version: 3.25.6
package com.microservices.grpc.order_product.dto;

public interface UpdateProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order_product.UpdateProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.order_product.Product product = 1;</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <code>.order_product.Product product = 1;</code>
   * @return The product.
   */
  com.microservices.grpc.order_product.entities.Product getProduct();
  /**
   * <code>.order_product.Product product = 1;</code>
   */
  com.microservices.grpc.order_product.entities.ProductOrBuilder getProductOrBuilder();
}
